name: CI/CD Pipeline
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - release

jobs:
  run_tests:
    uses: trench-live/devops_control_point_2/.github/workflows/test.yml@release

  security:
    uses: trench-live/devops_control_point_2/.github/workflows/security.yml@release
