name: CI/CD Pipeline

on:
  pull_request:
    branches: [release]
    types: [closed]

jobs:
  check_merge:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest
    steps:
      - name: Cancel non-merge runs
        run: exit 1

  run_tests:
    needs: check_merge
    uses: ${{ fromJSON(vars.paths).workflows.tests }}

  handle_results:
    needs: run_tests
    uses: ${{ fromJSON(vars.paths).workflows.result_handler }}
    secrets: inherit