name: CI/CD Pipeline

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [release]

jobs:
  run_tests:
    uses: ${{ fromJSON(vars.paths).workflows.tests }}

  handle_results:
    uses: ${{ fromJSON(vars.paths).workflows.result_handler }}
    needs: run_tests
    if: always()
    secrets: inherit