name: CI/CD Pipeline

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - release

jobs:
  tests:
    name: (TST) Run Tests
    uses: trench-live/devops_control_point_2/.github/workflows/test.yml@release