name: CI/CD Pipeline

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - 'feature/*'
      - 'hotfix/*'
      - 'release'


jobs:
  run_tests:
    uses: trench-live/devops_control_point_2/.github/workflows/test.yml@release

  security:
    needs: run_tests
    uses: trench-live/devops_control_point_2/.github/workflows/security.yml@release

  version_update:
    needs: security
    uses: trench-live/devops_control_point_2/.github/workflows/version_update.yml@release

  log_changes:
    needs: version_update
    uses: trench-live/devops_control_point_2/.github/workflows/log_changes.yml@release
    with:
      update_tag: ${{ needs.version_update.outputs.new_version }}

  docker_push:
    needs: [ version_update, log_changes ]
    uses: trench-live/devops_control_point_2/.github/workflows/docker_push.yml@release
    with:
      update_tag: ${{ needs.version_update.outputs.new_version }}
    secrets: inherit

  telegram_notify:
    needs: [ version_update, docker_push ]
    uses: trench-live/devops_control_point_2/.github/workflows/telegram_notify.yml@release
    with:
      update_tag: ${{ needs.version_update.outputs.new_version }}
    secrets: inherit

  deploy:
    needs: [ version_update, telegram_notify ]
    uses: trench-live/devops_control_point_2/.github/workflows/deploy.yml@release
    with:
      update_tag: ${{ needs.version_update.outputs.new_version }}
    secrets: inherit

  release:
    needs: [ version_update, deploy ]
    uses: trench-live/devops_control_point_2/.github/workflows/release.yml@release
    with:
      update_tag: ${{ needs.version_update.outputs.new_version }}
    secrets: inherit