name: CI/CD Pipeline

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - 'feature/*'
      - 'hotfix/*'
      - 'release'


jobs:
  run_tests:
    uses: trench-live/devops_control_point_2/.github/workflows/test.yml@release

  security:
    needs: run_tests
    uses: trench-live/devops_control_point_2/.github/workflows/security.yml@release

  version_update:
    needs: security
    uses: trench-live/devops_control_point_2/.github/workflows/version_update.yml@release

  log_changes:
    needs: version_update
    uses: trench-live/devops_control_point_2/.github/workflows/log_changes.yml@release
    with:
      update_tag: ${{ needs.version_update.outputs.new_version }}

  docker_push:
    needs: log_changes
    uses: trench-live/devops_control_point_2/.github/workflows/docker_push.yml@release
    with:
      update_tag: ${{ needs.version_update.outputs.new_version }}