name: CI/CD Pipeline
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - release

env:
  WORKFLOW_PATH: trench-live/devops_control_point_2/.github/workflows/test.yml@release

jobs:
  run_tests:
    uses: ${{ env.WORKFLOW_PATH }}