name: Docker Image Publish

on:
  workflow_call:
    inputs:
      update_tag:
        type: string
        required: true
        description: "Version tag (format: X.Y.Z)"

env:
  DOCKERHUB_USER: ${{ secrets.DOCKER_HUB_LOGIN }}
  REPO_NAME: 'trenchlive/devops_control_point_2'
  DOCKERFILE: 'Dockerfile'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_USER }}/${{ env.REPO_NAME }}:${{ inputs.update_tag }}
            ${{ env.DOCKERHUB_USER }}/${{ env.REPO_NAME }}:latest

      - name: Check for README
        id: readme_check
        run: |
          if [ -f "README.md" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Update description
        if: steps.readme_check.outputs.exists == 'true'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ env.REPO_NAME }}
          readme-filepath: ./README.md