name: Docker Image Publish

on:
  workflow_call:
    inputs:
      update_tag:
        type: string
        required: true
        description: "Version tag (format: X.Y.Z)"

env:
  REPO_NAME: 'devops_control_point_2'
  DOCKERFILE: 'Dockerfile'
  README: 'README.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.REPO_NAME }}:v${{ inputs.update_tag }}

      - name: Update Docker Hub description via API
        run: |
          DESCRIPTION=$(cat README.md | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
          JSON_DATA='{"full_description": "'"$DESCRIPTION"'"}'
          curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.DOCKER_HUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "$JSON_DATA" \
          "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.REPO_NAME }}/"