name: Docker Image Publish

on:
  workflow_call:
    inputs:
      update_tag:
        type: string
        required: true
        description: "Version tag (format: X.Y.Z)"
      docker_hub_login:
        type: string
        required: true
      docker_hub_password:
        type: string
        required: true

env:
  REPO_NAME: 'devops_control_point_2'
  DOCKERFILE: 'Dockerfile'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug inputs
        run: |
          echo "Login: ${{ inputs.docker_hub_login != '' }}"
          echo "Password: ${{ inputs.docker_hub_password != '' }}"        

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker_hub_login }}
          password: ${{ inputs.docker_hub_password }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ inputs.docker_hub_login }}/${{ env.REPO_NAME }}:v${{ inputs.update_tag }}  # Используем input

      - name: Update description
        if: contains(fromJson('["README.md", "README.MD", "readme.md"]'), 'README.md')
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ inputs.docker_hub_login }}  # Используем input
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  # Оставляем токен как секрет
          repository: ${{ env.REPO_NAME }}
          readme-filepath: ./README.md