name: Docker Image Publish

on:
  workflow_call:
    inputs:
      update_tag:
        type: string
        required: true
        description: "Version tag (format: X.Y.Z)"

env:
  REPO_NAME: 'devops_control_point_2'
  DOCKERFILE: 'Dockerfile'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secrets
        run: |
          echo "LOGIN: ${{ secrets.DOCKER_HUB_LOGIN != '' }}"
          echo "PASS: ${{ secrets.DOCKER_HUB_PASSWORD != '' }}"
          echo "TOKEN: ${{ secrets.DOCKER_HUB_TOKEN != '' }}