name: Security Checks

on:
  workflow_call:

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  antivirus:
    runs-on: ubuntu-latest
    name: Security Scan (Trivy)
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.14.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          exit-code: '0'
          format: 'table'
          severity: 'CRITICAL'

  security_linter:
    runs-on: ubuntu-latest
    name: Security Linter (Bandit)
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit scan
        run: bandit -r . -ll

  secrets_check:
    runs-on: ubuntu-latest
    name: TruffleHog Scan
    steps:
      - uses: actions/checkout@v4
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  add_sec_label:
    name: Add sec-passed label
    runs-on: ubuntu-latest
    needs: [antivirus, security_linter, secrets_check]
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['sec-passed']
              });
            } catch (error) {
              core.error('Failed to add label: ' + error.message);
              core.setFailed(error.message);
            }