name: Test Reporting

on: workflow_call
inputs:
  test_status:
    required: true
    type: string

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const { report } = require('./.github/scripts/test-reporter.js');
            await report({
              github: github,
              context: context,
              status: '${{ inputs.test_status }}'
            });