name: Test Result Handler
on: workflow_call

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Report status
        uses: ${{ fromJSON(vars.paths).workflows.reporting }}
        with:
          test_status: ${{ needs.run_tests.result }}