name: Update Version

on:
  workflow_call:

env:
  SCRIPT: trench-live/devops_control_point_2/.github/workflows/scripts/version_up.py

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Detect branch type
        id: branch
        run: |
          if [[ "${{ github.ref_name }}" == feature* ]]; then
            echo "TYPE=minor" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == hotfix* ]]; then
            echo "TYPE=patch" >> $GITHUB_OUTPUT
          fi

      - name: Update version
        run: |
          OLD_VER=$(head -n 1 version_info/version)

          python ${{ env.SCRIPT }} ${{ steps.branch.outputs.TYPE }}
          NEW_VER=$(head -n 1 version_info/version)

          git add version_info/version version_info/version_log
          git commit -m "[$NEW_VER] <- [$OLD_VER] ${{ steps.branch.outputs.TYPE }} up"