name: Version Update

on:
  workflow_call:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Determine branch type
        id: branch_type
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ "$BRANCH_NAME" == hotfix/* ]]; then
            echo "patch"
          else
            echo "minor"
          fi >> $GITHUB_OUTPUT

      - name: Run version update script
        run: python version_update.py ${{ steps.branch_type.outputs.version_type }}

      - name: Commit and push version changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update version [skip ci]"
          git push origin HEAD:${{ github.ref_name }}