name: Version Update

on:
  workflow_call:
    inputs:
      version_file_path:
        description: 'Path to version file'
        required: false
        default: 'version_info/version'
      version_log_path:
        description: 'Path to version log file'
        required: false
        default: 'version_info/version_log'
    secrets:
      workflow_token:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update_version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version_update.outputs.NEW_VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.workflow_token }}

      - name: Determine update type
        id: bump_type
        run: |
          if [[ $GITHUB_REF == refs/heads/feature/* ]]; then
            echo "minor"
          elif [[ $GITHUB_REF == refs/heads/hotfix/* ]]; then
            echo "patch"
          fi >> $GITHUB_OUTPUT

      - name: Run version update
        id: version_update
        env:
          VERSION_FILE: ${{ inputs.version_file_path }}
          VERSION_LOG_FILE: ${{ inputs.version_log_path }}
        run: |
          python "$GITHUB_WORKSPACE/.github/version_updater.py" "${{ steps.bump_type.outputs.result }}"
          echo "NEW_VERSION=$(cat ${{ inputs.version_file_path }})" >> $GITHUB_OUTPUT

      - name: Commit version changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ${{ inputs.version_file_path }} ${{ inputs.version_log_path }}
          git commit -m "[$(cat ${{ inputs.version_file_path }})] Version update"
          git tag -a "v$(cat ${{ inputs.version_file_path }})" -m "Version $(cat ${{ inputs.version_file_path }})"
          git push origin HEAD --tags

      - name: Add version label
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['v${{ steps.version_update.outputs.NEW_VERSION }}']
            })